import { Music, Note, Track } from '../utils/audio-utils';

const accompaniamentTracks = [
    new Track([
        Note.new("g#", 3, 5), null, Note.new("g#", 3, 5), null,
        Note.new("a#", 3, 5), null, Note.new("a#", 3, 5), null,
        Note.new("b", 3, 5), null, Note.new("b", 3, 5), null,
        Note.new("g#", 3, 5), null, Note.new("g#", 3, 5), null,
        Note.new("f#", 3, 5), null, Note.new("f#", 3, 5), null,
        Note.new("e", 3, 5), null, Note.new("e", 3, 5), null,
        Note.new("c#", 3, 5), null, Note.new("c#", 3, 5), null,
        Note.new("d#", 3, 5), null, Note.new("d#", 3, 5), null,
        Note.new("f#", 3, 5), null, Note.new("f#", 3, 5), null,
        Note.new("g#", 3, 5), null, Note.new("g#", 3, 5), null,
        Note.new("a#", 3, 5), null, Note.new("a#", 3, 5), null,
        Note.new("b", 3, 5), null, Note.new("b", 3, 5), null,
        Note.new("g#", 3, 5), null, Note.new("f#", 3, 5), null,
        Note.new("e", 3, 5), null, Note.new("c#", 3, 5), null
    ], "triangle", 2, 0.02, 11),
    new Track([
        Note.new("c", 2, 4), null, null, null,
        Note.new("f#", 2, 4), null, null, null,
        Note.new("c", 2, 4), null, Note.new("b", 2, 4), null,
        Note.new("f#", 2, 4), null, null, null,

        Note.new("c", 2, 4), null, null, null,
        Note.new("f#", 2, 4), null, null, null,
        Note.new("c", 2, 4), null, Note.new("a#", 2, 4), null,
        Note.new("f#", 2, 4), null, null, null,

        Note.new("c", 2, 4), null, null, null,
        Note.new("f#", 2, 4), null, null, null,
        Note.new("c", 2, 4), null, Note.new("b", 2, 4), null,
        Note.new("f#", 2, 4), null, null, null,

        Note.new("c", 2, 4), null, null, null,
        Note.new("f#", 2, 4), null, null, null,
        Note.new("c", 2, 4), null, Note.new("a#", 2, 4), null,
        Note.new("f#", 2, 4), null, null, null
    ], "square", 2, 0.005, 11)
];

const melodyTrack = new Track([
    Note.new("c", 5, 4),
    null,
    Note.new("c#", 5, 4),
    Note.new("d#", 5, 4),
    null,
    Note.new("e", 5, 4),
    Note.new("f#", 5, 4),
    null,
    Note.new("g#", 5, 4),
    Note.new("a#", 5, 4),
    null,
    Note.new("b", 5, 4),
    Note.new("a#", 5, 4),
    null,
    Note.new("g#", 5, 4),
    Note.new("f#", 5, 4),
    Note.new("e", 5, 4),
    null,
    Note.new("d#", 5, 4),
    Note.new("c#", 5, 4),
    null,
    Note.new("c", 5, 4),
    Note.new("c#", 5, 4),
    null,
    Note.new("d#", 5, 4),
    Note.new("e", 5, 4),
    null,
    Note.new("f#", 5, 4),
    Note.new("g#", 5, 4),
    null,
    Note.new("a#", 5, 4),
    Note.new("b", 5, 4),
    null,
    Note.new("a#", 5, 4),
    Note.new("g#", 5, 4),
    Note.new("f#", 5, 4),
    null,
    Note.new("e", 5, 4),
    Note.new("d#", 5, 4),
    null,
    Note.new("c#", 5, 4),
    Note.new("c", 5, 4),
    null,
    Note.new("c#", 5, 4),
    Note.new("d#", 5, 4),
    Note.new("e", 5, 4),
    null,
    Note.new("f#", 5, 4),
    Note.new("g#", 5, 4),
    Note.new("a#", 5, 4),
    null,
    Note.new("b", 5, 4),
    Note.new("a#", 5, 4),
    Note.new("g#", 5, 4),
    null,
    Note.new("f#", 5, 4),
    Note.new("e", 5, 4),
    Note.new("d#", 5, 4),
    null,
    Note.new("c#", 5, 4),
    Note.new("c", 5, 4)
], "triangle", 2, 0.01, 33);

export const music = new Music(
    [melodyTrack, ...accompaniamentTracks],
    260
);

